#!name=LightRoom
#!desc=LightRoom Pro Unlocker
#!homepage=https://your-custom-link.com

[MITM]
hostname = %APPEND% photos.adobe.io, cc-api-data.adobe.io, abp-profile-service.adobe.io

[Script]
LightRoom = type=http-response,pattern=^https:\/\/(photos|cc-api-data|abp-profile-service)\.adobe\.io\/.*account.*,requires-body=1,script-path=https://raw.githubusercontent.com/sowwnn/Make/refs/heads/crack/Lightroom.js